### ISSUE TITLE
Autocode version

### ISSUE THREAD

**Issue by rsodre** [0xEssential/opensea-discord-bot#1]
Hello.
I followed you here from the Autocode Discord, did you manage to finish the bot port to Audocode?
Is the Autocode bot source available?
Thanks,
Roger

**Comment by sbauch** [comment]
hey there, im not really familiar with autocode, so not really sure what this is about!

**Comment by rsodre** [comment]
hmm, I probably mixed conversations.
I'm making my bots on Autocode.com, it's super easy to use.
Cheers!
