### ISSUE TITLE
error not captured in api call

### ISSUE THREAD

**Issue by quaekr** [0xEssential/opensea-discord-bot#13]
receive this sometimes which causes the service to crash:

```
FetchError: invalid json response body at https://api.opensea.io/api/v1/events?offset=0&event_type=successful&only_opensea=false&occurred_after=1631264368&collection_slug=processed-art-mirage&asset_contract_address=0x94edd64585015a3bb06c6061a70fb63ef4bc3cef reason: Unexpected token < in JSON at position 0
```

assume it's just not handling the error

**Comment by rssnyder** [comment]
I believe this has something to do with their spam detection. 
![image](https://user-images.githubusercontent.com/7338312/142463164-2574713b-eea0-4857-b5d3-ccb864dbeff3.png)

**Comment by ppswaggy** [comment]
I’m having the exact same thing. Anyway to get past this? 
![066CD171-1842-4235-AA63-8F061E3BB822](https://user-images.githubusercontent.com/94812907/142849009-92b09e94-b5e5-460a-8943-ea4bb537d232.png)

**Comment by rssnyder** [comment]
hey all i was able to solve this by requesting an API token for opensea, and then adding the token into the header: https://github.com/rssnyder/opensea-discord-bot/pull/1

get your token here: https://docs.opensea.io/reference/request-an-api-key

**Comment by darrensapalo** [comment]
Thanks @rssnyder , also added #17 which should give more descriptive error messages for rate limiting errors.
