### ISSUE TITLE
Heroku Error

### ISSUE THREAD

**Issue by checkit** [0xEssential/opensea-discord-bot#20]
Any insights as to why Heroku is throwing this error?

We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by rssnyder** [comment]
The policy is found [here](https://www.salesforce.com/content/dam/web/en_us/www/documents/legal/Agreements/policies/ExternalFacing_Services_Policy.pdf), its pretty broad and I am guessing is there to give them the right to shut down your services if you use them for malicious purposes.

Were you using this code in any way that could violate those terms? The code is just a tool, heroku seems to be stopping you based on usage.

Id suggest opening a support ticket? This is unrelated to the project so I am going to close for now.
