### ISSUE TITLE
Heroku Not Allowing

### ISSUE THREAD

**Issue by ppswaggy** [0xEssential/opensea-discord-bot#21]
![85DD940A-B0DB-4CC2-918D-FF765F4F75C5](https://user-images.githubusercontent.com/94812907/149872590-ee3e0158-ebfb-437c-bb6f-02368535d3d2.jpeg)

Thought I’d bring this to your attention? Anyway to fix this? It’s also worth mentioning I’ve used two heroku opensea discord bots & they’re both getting this message as-well.

**Comment by rssnyder** [comment]
dup of https://github.com/0xEssential/opensea-discord-bot/issues/20

"The policy is found here, its pretty broad and I am guessing is there to give them the right to shut down your services if you use them for malicious purposes.

Were you using this code in any way that could violate those terms? The code is just a tool, heroku seems to be stopping you based on usage.

Id suggest opening a support ticket? This is unrelated to the project so I am going to close for now."

heroku is not the only place you can run this code. as a cloud platform they can choose what to allow and they seems to have decided against this.

try using [github actions](https://github.com/0xEssential/opensea-discord-bot/blob/main/.github/workflows/run.yml.example) to run it for free, or try another cloud platform.
